apiVersion: v1
kind: Namespace
metadata:
  name: all-limits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-all-limits
  namespace: all-limits
  labels:
    app: test-pod
    test-type: all-limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
      test-type: all-limits
  template:
    metadata:
      labels:
        app: test-pod
        test-type: all-limits
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
