apiVersion: v1
kind: Namespace
metadata:
  name: no-cpu-limit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-memory-only
  namespace: no-cpu-limit
  labels:
    app: test-pod
    test-type: memory-only
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
      test-type: memory-only
  template:
    metadata:
      labels:
        app: test-pod
        test-type: memory-only
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
